#!/bin/sh

# Copyright 2011, Trent Nelson.

#----------------------------------------------------------------------------#
# globals                                                                    #
#----------------------------------------------------------------------------#
force=0
dryrun=0
master="https://raw.github.com/tpn/mysqlx/master/mysqlx"
verbose=0
dataset=""
command=""
options=""
prepared=0
mountpoint=""
base_dataset=""
base_mountpoint=""

#----------------------------------------------------------------------------#
# cruft                                                                      #
#----------------------------------------------------------------------------#
_cwd=`pwd`
_dir=`dirname $0`
echo $_dir | grep '^\.' > /dev/null 2>&1 && \
    _dir=${_cwd}`echo ${_dir} | sed -e 's/^\.//'`
_mysqlx=${_dir}/mysqlx
_mysqlx_sudo=${_mysqlx}_sudo

if [ ! -f $_mysqlx ]; then
    echo error: $_mysqlx not a normal file
    exit 1
fi

#----------------------------------------------------------------------------#
# error handlers                                                             #
#----------------------------------------------------------------------------#
set -o errexit
set -o nounset

#----------------------------------------------------------------------------#
# public helpers                                                             #
#----------------------------------------------------------------------------#
cmd() {
    local _verbose
    _verbose=0
    if [ $dryrun -ne 0 -o $verbose -eq 1 ]; then
        _verbose=1
    fi
    if [ $_verbose -eq 1 ]; then
        echo $*
    fi

    if [ $dryrun -eq 0 ]; then
        eval $*
    fi
}

die() {
    echo $*
    exit 1
}

#----------------------------------------------------------------------------#
# private helpers                                                            #
#----------------------------------------------------------------------------#
_resolve() {

    local _mntpt _zfs_mntpt _p _dataset
    dataset=""
    mountpoint=""
    base_dataset=""
    base_mountpoint=""

    _p=$1

    # . -> `pwd`
    if [ "$_p" = "." ]; then
        _p=`pwd`
    fi

    # ./foo -> foo
    echo $_p | egrep '^\.\/' > /dev/null && \
        _p=`echo $_p | sed -e 's:^\./::'`

    # prohibit ^.. or /.
    echo $_p | egrep '^\.\.|\/\.|\\' > /dev/null && {
        echo invalid path: $_p
        return 1
    }

    # if it doesn't start with /, but has multiple slashes in it,
    # it might be a dataset (should probably just check to see if
    # the name starts with a zpool name)
    if `echo $_p | egrep '^[^/]+/' > /dev/null`; then
        dataset=`zfs list -H -t filesystem -o name | grep "^${_p}$"`
        if [ -n "$dataset" ]; then
            mountpoint=`zfs get -H -o value mountpoint $dataset`
            return 0
        fi
    fi

    # if it doesn't start with /, abs it via `pwd`
    if `echo $_p | grep -v '^/' > /dev/null`; then
        _mntpt=`pwd`/$_p
    else
        _mntpt=$_p
    fi

    if [ "$command" = "create" ]; then
        _mntpt=`dirname $_mntpt`
    fi

    # verify there's a corresponding mysql mountpoint by the same name
    _zfs_mntpt=`zfs list -H -o mountpoint | grep "^${_mntpt}$"`
    if [ -z "$_zfs_mntpt" ]; then
        echo error: $_mntpt is not backed by a mysql dataset
        return 1
    fi
    if [ "$_zfs_mntpt" != "$_mntpt" ]; then
        echo "mountpoint mismatch: $_zfs_mntpt vs $_mntpt"
        return 1
    fi

    # look for a corresponding mysql dataset for the mountpoint
    _dataset=`zfs list -H -t filesystem -o name,mountpoint | \
             grep '	'${_mntpt}'$' | cut -f 1`

    if [ -z "$_dataset" ]; then
        die "error: invariant violated: couldn't resolve \
             mysql dataset for mountpoint $_mntpt"
    fi

    if [ "$command" = "create" ]; then
        base_dataset=$_dataset
        base_mountpoint=$_mntpt
        dataset=$_dataset/$_p
        mountpoint=$_mntpt/$_p
    else
        dataset=$_dataset
        mountpoint=$_mntpt
    fi

    return 0
}

_prepare_cmd() {
    local _p _opts
    command=$1
    shift
    [ $# -eq 0 ] && die "_prepare_cmd incorrect usage"
    options=""

    eval _p=\"\${$#}\"
    _resolve $_p || exit 1

    _opts=""
    while : ; do
        [ $# -eq 1 ] && break
        _opts="$_opts $1"
        shift
    done

    options=$_opts
}

#----------------------------------------------------------------------------#
# main mysql methods for public consumption and great justice                  #
#----------------------------------------------------------------------------#

zfs_allowed() {
    local _require_sudo _cmd _p _u _group _perms
    _require_sudo=0
    if [ "$1" = "require-sudo" ]; then
        _require_sudo=1
        shift
    fi

    _cmd=$1
    _p=$2

    if [ `id -u` -eq 0 ]; then
        if [ -z "${SUDO_USER:-}" ]; then
            if [ $_require_sudo -eq 1 ]; then
                echo error: sudo required for $_cmd $_p
                return 1
            fi
            return 0
        else
            _u=$SUDO_USER
        fi
    else
        if [ $_require_sudo -eq 1 ]; then
            echo error: sudo required for $_cmd $_p
            return 1
        fi
        _u=`id -un`
    fi

    _group=@`zfs allow $_p | egrep "^	user $_u @[a-zA-Z0-9]+$" | \
            cut -f 2 -d '@'`

    if [ $? -ne 0 -o -z "$_group" ]; then
        echo "error: no permissions set for user $_u on $_p"
        return 1
    fi

    mysql allow $_p | egrep "^	$_group ($_cmd|.+,$_cmd)(,|$)" \
        > /dev/null 2>&1

    if [ $? -ne 0 ]; then
        echo "error: user $_u does not have '$_cmd' permission" \
             "set for $dataset"
        return 1
    fi

    return 0
}

zfs_cmd() {
    _prepare_cmd $*
    cmd mysql $command $options $dataset
}

mkpasswd() {
    openssl rand -base64 40 | sed "s/[^a-zA-Z0-9]//g" | cut -c 1-32
}

mysql_create_database() {
    local _db _passwd _oldwd
    _db=$1
    _passwd=`mkpasswd`

    mr << EOF
create database $_db;
create user $_db identified by '$_passwd';
grant all on $_db.* to $_db@localhost identified by '$_passwd';
flush privileges;
EOF

    cat ~/.my.cnf.root | sed \
        -e "s/^user .*\$/user    = $_db/;" \
        -e "s/^password .*\$/password    = $_passwd/;" \
            > ~/.my.cnf.$_db

    _oldwd=`pwd`
    cd ~/mysql/db

    zc $_db.tmp
    sudo cpdup -Iq $_db $_db.tmp
    sudo rm -rf $_db
    zmv $_db.tmp $_db

    cd $_oldwd
}

mklinks() {
    local _f _l _q

    for _f in $(cat $_mysqlx | egrep '^    m[a-z]{1,3}.*# ln$' | \
                cut -f 1 -d '|' | sed 's/    //;'); do
        _l=${_dir}/$_f
        if [ -e $_l ]; then
            if [ $force -eq 0 ]; then
                if [ $verbose -eq 1 ]; then
                    echo skipping $_l...
                fi
            else
                ln -sf $_mysqlx $_l
                echo "created link '$_l'"
            fi
        else
            ln -s $_mysqlx $_l
            echo "created link '$_l'"
        fi
    done
    return
}

rmlinks() {
    local _l _q _f

    _f=""
    if [ $force -eq 1 ]; then
        _f="-f"
    fi

    for _l in $(find ${_dir} -type l -lname $_mysqlx); do
        if [ $verbose -eq 1 ]; then
            echo removing $_l...
        fi
        rm $_f $_l
    done

    local _need_force
    _need_force=0
    for _l in $(cat $_mysqlx | egrep '^    z[a-z]{1,3}.*# ln$' | \
                cut -f 1 -d '|' | sed 's/    //;'); do
        if [ -L $_l ]; then
            if [ $force -eq 1 ]; then
                rm -f $_l
                echo "removed link '$_l'"
            else
                echo "error: $_l is a link to something other than mysqlx"
                _need_force=1
            fi
        elif [ -e $_l ]; then
            if [ $force -eq 1 ]; then
                rm -rf $_l
                echo "removed '$_l'"
            else
                echo "error: $_l is not a symbolic link"
                _need_force=1
            fi
        fi
    done
    if [ $_need_force -eq 1 ]; then
        echo "re-run with -f argument to force removal (e.g. 'mysqlx -f rmlinks')"
    fi
}

ask() {
    local question default answer
    question=$1
    default=$2
    read -p "${question} [${default}] " answer
    if [ -z "${answer}" ]; then
        answer=${default}
    fi
    echo ${answer}
}

yesno() {
    local question default answer
    question=$1
    default=$2
    while :; do
        answer=$(ask "${question}" "${default}")
        case "${answer}" in
        [Yy]*)  return 0;;
        [Nn]*)  return 1;;
        esac
        echo "Please answer yes or no."
    done
}

update() {
    if [ -d "${_dir}/.git" ]; then
        echo error: not updating, git directory detected: ${_dir}/.git
        exit 1
    fi

    local _f _o
    _f=`mktemp /tmp/mysqlx.XXXXX` || die "couldn't create temp file"
    _o=`mktemp /tmp/mysqlx.XXXXX` || die "couldn't create temp file"
    fetch -o $_f $master > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo failed to fetch $master
        rm $_f
        rm $_o
    fi
    if [ `md5 -q $_f` = `md5 -q $_mysqlx` ]; then
        echo $_mysqlx is already up to date
        rm -f $_f || true
        rm -f $_o || true
    else
        echo downloaded new version of mysqlx to $_f
        $_mysqlx rmlinks > /dev/null 2>&1 || true
        echo backing up existing version of $_mysqlx to $_o...
        cp $_mysqlx $_o
        echo moving new version $_f to $_mysqlx...
        mv $_f $_mysqlx
        if ! yesno "keep backup $_o?" "n"; then
            rm $_o || true
        fi
        chown root:wheel $_mysqlx
        chmod 555 $_mysqlx
        sh $_mysqlx mklinks
    fi
}

usage() {
    echo "usage: xxx todo"
    exit 1
}

#----------------------------------------------------------------------------#
# main                                                                       #
#----------------------------------------------------------------------------#
main() {
    local _cmd _perm _p
    _perm=""
    _cmd=$1
    shift
    case "$_cmd" in
    mysqlx)
        main $*
        ;;
    mklinks)
        mklinks
        ;;
    rmlinks)
        rmlinks
        ;;
    mc|create) # ln
        [ $# -lt 1 ] && {
            echo usage: mc dbname
            return 1
        }
        mysql_create_database $1
        ;;
    mr|mysql-root) # ln
        mysql --defaults-file=~/.my.cnf.root
        ;;
    mf|mysql-fly) # ln
        mysql --defaults-file=~/.my.cnf.fly
        ;;
    mst|mysql-test) # ln
        mr << EOF
show databases;
select count(*) from mysql.db;
EOF
        ;;
    zd|destroy) # xln
        [ $# -lt 1 ] && usage
        _prepare_cmd destroy $*
        zfs_allowed $command $dataset || return 1
        if [ -n "${SUDO_USER:-}" ]; then
            cmd mysql $command $options $dataset
        else
            sudo $_mysqlx $command $options $dataset
        fi
        ;;
    zs|set) # xln
        zfs_cmd set $*
        ;;
    zg|get) # xln
        zfs_cmd get $*
        ;;
    update)
        update
        ;;
    zm|mount) # xln
        _prepare_cmd mount $*
        zfs_allowed require-sudo mount $dataset || return 1
        cmd mysql mount $dataset || return 1
        ;;
    set-canmount-on)
        [ $# -ne 1 ] && usage
        _resolve $1
        zfs_allowed require-sudo canmount $dataset || return 1
        cmd mysql set canmount=on $dataset
        ;;
    zpd|resolve-dataset) # xln
        local _p
        _p=""
        while : ; do
            [ $# -eq 0 ] && break
            _resolve $1 || break
            _p="$_p $dataset"
            shift
        done
        echo $_p
        ;;
    zpm|resolve-mountpoint) # xln
        local _p
        _p=""
        while : ; do
            [ $# -eq 0 ] && break
            _resolve $1 || break
            _p="$_p $mountpoint"
            shift
        done
        echo $_p
        ;;
    *)
        echo error: unknown command: $_cmd
    esac

    return
}

#echo 0: $0
#[ $# -eq 0 -a $0 != "mr"  ] && usage

if [ $# -gt 0 ]; then
    while : ; do
        case "$1" in
        -v)
            verbose=1
            shift
            ;;
        -d)
            dryrun=1
            shift
            ;;
        -f)
            force=1
            shift
            ;;
        *)
            break
        esac
    done
fi

#[ $# -eq 0 ] && usage

if [ $force -eq 1 ]; then
    if [ $# -gt 0 ]; then
        if [ "$1" != "mklinks" -a "$1" != "rmlinks" ]; then
            echo "error: -f (force) only applicable to mklinks and rmlinks"
            exit 1
        fi
    fi
fi

main `basename $0` $*

# vim:set ts=8 sw=4 sts=4 expandtab syntax=sh:
